---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---
```{r}
library(ggplot2)
```


# 1.1. KTC Boostrap normal

```{r}
# Ex1:
surimi <- c(41.28, 45.16, 34.75, 40.76, 43.61, 39.05, 41.20, 41.02, 41.33,
40.61, 40.49, 41.77, 42.07, 44.83, 29.12, 45.59, 41.95, 45.78,
42.89, 40.42, 49.31, 44.01, 34.87, 38.60, 39.63, 38.52, 38.52,
43.95, 49.08, 50.52, 43.85, 40.64, 45.86, 41.25, 50.35,
45.18, 39.67, 43.89, 43.89, 42.16)
```

```{r}
mu_surimin <- mean(surimi)
mu_surimin
```

```{r}
# Qua trinh boostrap mau
n_surimi <- length(surimi)
nR <- 1000
mu_surimi_boot <- numeric(nR)
set.seed(23)
for (i in 1:nR) {
id_boot <- sample(1:n_surimi, size = n_surimi, replace = TRUE)
surimi_boot <- surimi[id_boot]
mu_surimi_boot[i] <- mean(surimi_boot)
}
```

```{r}
mean(mu_surimi_boot)
```
```{r}
# Do chech
b_surimin = mean(mu_surimi_boot) - mu_surimin
b_surimin
```


```{r}
# Do lech chuan boostrap
se_surimi_boot <- sd(mu_surimi_boot)
se_surimi_boot
```
```{r}
ci_surimi_norm_bts <- mu_surimin - b_surimin +
c(-1, 1)*se_surimi_boot*qnorm((1 + 0.95)/2)
ci_surimi_norm_bts
```


```{r}
mu_surimin - b_surimin +se_surimi_boot*qnorm(1-0.05/2)
```


```{r}
mu_surimin - b_surimin -se_surimi_boot*qnorm(1-0.05/2)
```
```{r}
# histogram
library(ggplot2)
ggplot(data = data.frame(t = mu_surimi_boot), mapping = aes(x = t)) +
geom_histogram(fill = "gray80", color = "black", bins = 20) +
geom_vline(xintercept = mean(surimi), color = "blue",
linetype = "dashed") +
xlab("bootstrap mean") + ylab("Frequency") +
theme_bw()

```

# 1.2. KTC basic
```{r}
mu_surimi_boot_incr <- sort(mu_surimi_boot)
```


```{r}
ci_surimi_basic_bts <- 2*mu_surimin - mu_surimi_boot_incr[floor(nR*c(1 - 0.05/2, 0.05/2))]
ci_surimi_basic_bts
```
# 1.3. Khoảng tin cậy bootstrap percentile

```{r}
ci_surimi_perc_bts <- mu_surimi_boot_incr[floor(nR*c(0.05/2, 1 - 0.05/2))]
ci_surimi_perc_bts
```

# 1.4 Khoảng tin cậy bootstrap studentized
```{r}
mu_surimi_boot <- numeric(nR)
se_mu_surimi_boot <- numeric(nR)
set.seed(23)
for (i in 1:nR) {
id_boot <- sample(1:n_surimi, size = n_surimi, replace = TRUE)
surimi_boot <- surimi[id_boot]
mu_surimi_boot[i] <- mean(surimi_boot)
se_mu_surimi_boot[i] <- sd(surimi_boot)/sqrt(n_surimi)
}
```


```{r}
z_surimi_boot <- (mu_surimi_boot - mu_surimin)/se_mu_surimi_boot
```

```{r}
z_surimi_boot_qt_095 <- sort(z_surimi_boot)[floor(nR*c(1 - 0.05/2 , 0.05/2))]
```

```{r}
se_mu_surimi <- sd(surimi)/sqrt(n_surimi)
ci_surimi_stud_bts <- mu_surimin - se_mu_surimi*z_surimi_boot_qt_095
ci_surimi_stud_bts
```

# 2 Thu vien boost

```{r}
mean_boot_fun <- function(data, ind){
  n <- length(data)
  data <- data[ind]
  mu_est <- mean(data)
  mu_var <- var(data)/n
  return(c(mu_est, mu_var))
}
```


```{r}
library(boot)
out_boot = boot(data=surimi, statistic = mean_boot_fun, R=1000, sim="ordinary")
out_boot
```

```{r}
boot.ci(boot.out = out_boot, conf = 0.95, type = c("norm", "basic", "stud", "perc", "bca"))
```
# BT
## BT1

```{r}
data <- read.table('birthwt.txt', header = TRUE)
head(data)
```



```{r}
# a) ktc boostrap cho trung bình của lwt
lwt_data <- data$lwt
mean_boot_lwt <- function(data, ind){
  n <- length(data)
  data <- data[ind]
  mu_data <- mean(data)
  mu_var <- var(data)/n
  return (c(mu_data, mu_var))
}
```

```{r}
mean(lwt_data)
```


```{r}
set.seed(23)
boot_out <- boot(data=lwt_data, statistic = mean_boot_lwt, R=1000, sim='ordinary')
boot_out
```

```{r}
boot.ci(boot.out = boot_out, type='all')
```
```{r}
# b) trung vi cua age
age_data <- data$age
med_boot_age <- function(data, ind){
  n <- length(data)
  data <- data[ind]
  mu_data <- median(data)
 # mu_var <- # uoc luong phuong sai cua medi
  return (c(mu_data))
}
```

```{r}
median(age_data)
```


```{r}
set.seed(23)
boot_out <- boot(data=age_data, statistic = med_boot_age, R=1000, sim='ordinary')
boot_out
```

```{r}
boot.ci(boot.out = boot_out, type=c('norm', 'basic', 'perc'))
```
```{r}
# c) tương quan giữa lwt và bwt
cor_data <- data[,c("lwt", "bwt")]
cor_boot <- function(data, ind){
  n <- nrow(data)
  data <- data[ind,]
  mu_data <- cor(data$lwt, data$bwt)
  # uoc luong cho variance cua cor
  cor_boot2 = numeric(n)
  for (i in 1:n){
    #m <- nrow(data)
    id <- sample(1:n, 200, replace = TRUE)
    data_boot <- data[id,]
    cor_boot2[i] <- cor(data_boot$lwt, data_boot$bwt)
  }
   mu_var <- var(cor_boot2) #uoc luong phuong sai cho cor
  return (c(mu_data, mu_var))
}
```


```{r}
set.seed(23)
boot_out <- boot(data=cor_data, statistic = cor_boot, R=1000, sim='ordinary')
boot_out
```

```{r}
boot.ci(boot.out = boot_out, conf=0.95, type=c('norm', 'basic', 'perc', 'stud'))
```


