---
title: "R Notebook"
output: html_notebook
---
```{r}
library(readxl)
```

# Bước 1: Load data
```{r}
data <- read_excel('la-liga-2015-2016.xlsx')
head(data)
```
```{r}
data <- as.data.frame(data)
```

# Bước 2: EDA data
```{r}
# check shape
dim(data)
```
```{r}
# check type
str(data)
```

```{r}
# check columns name
names(data)
```

```{r}
# exclude useless columns
cols = c(1, 3, 9)
data <- data[,-cols]
```

```{r}
names(data)
```


```{r}
# PCA
pc <- princomp(data, fix_sign=TRUE)
summary(pc)
```

```{r}
# scree plot
screeplot(pc, type='line')
```

```{r}
n <- nrow(data)
```

```{r}
eig <- eigen(cov(data)*(n-1)/n)
eig$value
```

```{r}
pc$sdev^2
```

```{r}
pc$sdev^2 - eig$value
```

```{r}
round(-1.818989e-12, 4)
```
```{r}
# eigen vector
loadings(pc)
```

```{r}
# check cov giữa các component
corrplot(cov(pc$scores), addCoef.col = "gray", is.corr = FALSE)
```
```{r}
names(data)
```
```{r}
center_data <- scale(data, center = TRUE, scale = FALSE)
center_data
```
```{r}
mean(data$Goals.scored)
```



```{r}
 # The scores are A’ * (X_i - mu). We center the data with scale() # and then multiply each row by A’
A <- eig$vectors
scores <- scale(data, center = TRUE, scale = FALSE)%*% A
scores
```

```{r}
pc$scores
```

```{r}
pc$scores + scores
```

```{r}
# tìm lại được X sau khi đã pca
 # Reconstruct the data from all the principal components
 head(sweep(pc$scores %*% t(pc$loadings), 2, pc$center, "+"))
```

```{r}
 ###############  standardize the dataset prior to do a PCA #####
 # Use cor = TRUE to standardize variables (all have unit variance) # and avoid scale distortions
 pc <- princomp(x = data, cor = TRUE, fix_sign = TRUE)
 summary(pc)

 biplot(pc, cex = 0.75)
```

```{r}
############ PCR ########
 # A linear model is problematic
 mod <- lm(Points ~ . - Wins - Draws - Loses - Matches.without.conceding, data = data)
 summary(mod) # Lots of non-significant predictors
 #We try to clean the model
 modBIC <- MASS::stepAIC(mod, k = log(nrow(data)), trace = 0)
 summary(modBIC) # Better, but still unsatisfactory
```


```{r}
# Also, huge multicollinearity
 car::vif(modBIC)
```
```{r}
# A quick way of removing columns without knowing its position
 laligaRed <- subset(data, select = -c(Points, Wins, Draws, Loses, Matches.without.conceding))
```



```{r}
# PCA without Points, Wins, Draws, Loses, and Matches.without.conceding => PCA các biến độc lập còn lại
 pcaLaligaRed <- princomp(x = laligaRed, cor = TRUE, fix_sign = TRUE)
 summary(pcaLaligaRed) # l = 3 gives 86% of variance explained
 pcaLaligaRed$loadings
```


```{r}
# Interpretation of PC1 and PC2
 biplot(pcaLaligaRed)
 # PC1: attack performance of the team
```

```{r} 
#Create a new dataset with the response + principal components
 laligaPCA <- data.frame("Points" = laliga$Points, pcaLaligaRed$scores) # Regression on all the principal components
 modPCA <- lm(Points ~ ., data = laligaPCA)
 summary(modPCA) # Predictors clearly significative -- same R^2 as mod
```
```{r}
car::vif(modPCA) # No problems at all
```

```{r}
modPCA3
```


```{r}
# Using the first three components
  modPCA3 <- lm(Points ~ Comp.1 + Comp.2 + Comp.3, data = laligaPCA) 
  summary(modPCA3)
```
```{r}
modPCA3$coefficients
```
```{r}
pcaLaligaRed$loadings[, 1:3]
```
```{r}
modPCA3$coefficients
```


```{r}
alpha[-1]
```


```{r}
# Coefficients associated to each original predictor (gamma)
(alpha <- modPCA3$coefficients)
(gamma <- pcaLaligaRed$loadings[, 1:3] %*% alpha[-1]) # Slopes
(gamma <- c(alpha[1] - pcaLaligaRed$center %*% gamma, gamma) )# Intercept
```

```{r}
# principal component does quite well
  modPCABIC <- MASS::stepAIC(modPCA, k = 2 * log(nrow(laliga)), trace = 0) 
  summary(modPCABIC)
```


```{r}
 # Predictions for FCB and RMA (although they are part of the training sample) 
  newPredictors <- laligaRed[1:2, ]
  newPredictors <- scale(newPredictors, center = pcaLaligaRed$center, scale = pcaLaligaRed$scale) # Centered and scaled
  newScores <- t(apply(newPredictors, 1,function(x) t(pcaLaligaRed$loadings) %*% x))
  newScores
```

```{r}
 # We need a data frame for prediction
  newScores <- data.frame("Comp" = newScores)
  predict(modPCABIC, newdata = newScores, interval = "prediction") #
  # Reality
  laliga[1:2, 1]
```


